[package]
name = "netmonrs"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.27"
ratatui = "0.26"
clap = { version = "4.5", features = ["derive"] }
regex = "1.10"
chrono = "0.4" # Для времени в логах
